# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Copy files
      run:  cp -r /home/kixrepository/_work/krepo/krepo/*.html  /home/krepo/
    - name: Copy save
      run:  cp -r /home/kixrepository/_work/krepo/krepo/save.php  /home/krepo/
    - name: Copy JS
      run:  cp -r /home/kixrepository/_work/krepo/krepo/shared.js  /home/krepo/
